### ISSUE TITLE
Rebuild with build 2.0.0 support

### ISSUE THREAD

**Issue by coastalgit** [MohiuddinM/i18n#14]
Can a package update be made using [build pkg 2.0.0](https://pub.dev/packages/build/changelog) and [quick_log pkg 4.0.3](https://pub.dev/packages/quick_log/changelog) please? I am getting conflicts with other dependencies (e.g. json_serializable 4.0.3)

**Comment by MohiuddinM** [comment]
I published a new version, containing the requested changes
