### ISSUE TITLE
Change output file name

### ISSUE THREAD

**Issue by BjoernPetersen** [MohiuddinM/i18n#2]
The generated dart files have `.i18n.dart` instead of the common `.g.dart` filename extension used by other packages. It would be nice if this package generated `.g.dart` files too so users don't have to extend their `.gitignore` for this package.

**Comment by MohiuddinM** [comment]
This package is different form some other packages. Usually in other packages the generated files are a part of another file which is imported into other parts of code. But here the generated files are independent, and not part of any other class.
