### ISSUE TITLE
How to setup this library correctly

### ISSUE THREAD

**Issue by rekire** [MohiuddinM/i18n#20]
I like the simplicity of the way how this is configured, however I don't get how to install this correctly.

I found in the documentation _"... run the webdev tool, or build_runner directly, and use your messages like this:"_ well fine, but **how** can I do this?

Do I need to choose the translation really by hand? I'm not really sure how I should select the translation correctly.

What I actually need to know is:
- What dependencies do I need to add to my `pubspec.yaml`?
- How do I generate exactly those i18n classes?
- How is the language of the user chosen?
- Is support for region suffixes? Like de-DE, de-AT or de-CH?

My speculation that I need the dependency `118n` and the dev dependency `build_runner: any`.  
I know that I can get the current language of the user by using `String language = Localizations.localeOf(context).languageCode;` but how can I use the knowledge to choose the correct translation dynamically? Will it fallback automatically to the default language without a locale suffix?

**Comment by rekire** [comment]
I found out the most relevant parts, so that I can answer my own questions now.

The modifications to the `pubspec.yaml` are:
- Raise the min sdk version to 2.12.0 for null safety when not done yet:
  ```yaml
  environment:
    sdk: ">=2.12.0 <3.0.0"
  ```
- The dependency itself:
  ```yaml
  dependencies:
    flutter:
      sdk: flutter
    # ...
    i18n: any
  ```
- The dev dependency to `build_runner` which is used as code generator:
  ```yaml
  dev_dependencies:
    flutter_test:
      sdk: flutter
    build_runner: any
  ```

I'm using it like this:
```dart
import 'i18n/login.i18n.dart';
import 'i18n/login_de.i18n.dart';

class Translation {
  late final Login login;

  Translation(BuildContext context) {
    String language = Localizations.localeOf(context).languageCode;
    this.login = language == 'de' ? LoginDe() : Login();
  }
}
```

You need to instantiate it with the `BuildContext` to choose the language for my code. Then you can use it simple and easy:

```dart
@override
Widget build(BuildContext context) {
  translation = Translation(context).login;

  return Scaffold(
      appBar: AppBar(
        title: Text(translation.title), // <- here I'm actually using it
        brightness: Brightness.dark,
      ),
// ...
```

To generate the dart files you need to execute:

    flutter packages pub run build_runner watch

This is actually in the readme, but I missed it.

If would be nice to know if you agree with me and if you would like to get a PR to share this knowledge

**Comment by NotTsunami** [comment]
One observation that I noticed when I began working with this project was the strict naming scheme required for the yaml files. This isn't explicitly mentioned in the README, but if you start poking through the code, you'll see it's required:

The yaml files _must_ be in the format of `*.i18n.yaml`, with the asterisk in my case being the language code (es, de, fr, etc).

That being said, this is still the best approach I have seen to i18n in Flutter and I am loving working with it. The only drawback to this library is the lack of documentation, but some of the points mentioned here could easily be baked into a README refresh and solve that issue 😃

**Comment by MohiuddinM** [comment]
@rekire Sorry for overlooking the issue. I have added an example of how to use it in a Flutter app. So basically you can create an InheridtedWidget (similar to MediaQuery or Theme).

https://github.com/MohiuddinM/i18n/tree/master/flutter_example
