### ISSUE TITLE
Question: Why should I add the yaml files to pubspec.yaml

### ISSUE THREAD

**Issue by erabti** [MohiuddinM/i18n#7]
I get this error if I don't add them in pubspec.yaml:

`Error: unable to find directory entry in pubspec.yaml: **/lib/presentation/core/i18n/translations/`
Why does the generator have to have the files as an asset?
When using other generators I don't have to add source files. I only need the generated files in my source code, I don't need the yaml files to be added to my assets which will increase bundle size.

**Comment by MohiuddinM** [comment]
You don't need to add yaml files to pubspec. Can your provide more details to reproduce?
