### ISSUE TITLE
What i18n package add by forking i69n one

### ISSUE THREAD

**Issue by BeliliFahem** [MohiuddinM/i18n#8]
Hi , my question is simple, what does the i18n package add by forking the [i69n](https://pub.dev/packages/i69n) package ? 
Will the evolutions of the i69n be carried over to i18n ?

**Comment by MohiuddinM** [comment]
@BeliliFahem This project is currently being supported, and any useful additions in the other package will be added of course. Current differences are better name, and no runtime dependency (use as `dev_dependencies`)
