### ISSUE TITLE
[Enhancement] Generating an interface

### ISSUE THREAD

**Issue by shovelmn12** [MohiuddinM/i18n#9]
I really like your approach for this package, makes things much easier.
I just have an idea for an enhancement that would make it even better.
When im using this package I am creating localization classes like the official docs describe, with `LocalizationsDelegate`.
And then create an extensions to `BuildContext` that gets me the current strings (they are depended on the locale of course), something like `context.strings` usually. But in order to create that i need to use `strings` as a dynamic, because I dont know what language is currently being used.
So I was thinking if the generator could also generate an interface that will generalize the strings. 
For example I have english, spanish, etc... so each of them will have a class of its own `EnglishStrings`, `SpanishStrings` etc... if all of them implements an interface or some other abstract class when fetching ANY language you can just return that interface or abstract class instead of dynamic so you will know what strings you have or not...

The interface should include all params, if one language have an extra param `extra` so all others should return null, empty string or maybe throw an unimplemented exception?

Hopefully you get the idea and why it would simplify the work with this package..

P.S: another cool thing is to generate `AppLocaliztion` and `LocalizationsDelegate<AppLocalization>` so it would work flawlessly with flutter.

**Comment by MohiuddinM** [comment]
If I understand your suggestion correctly, then it is already implemented.
Same type is used for both English and German translations:
https://github.com/MohiuddinM/i18n/blob/f0428513fcddc6c26d8c96e4c77b9003ba8aef51/example/main.dart#L14

**Comment by shovelmn12** [comment]
no thats not what i meant.

example: 2 languages eng and heb

generated classes:
```
class Hebrew {
	const Hebrew();
	AuthHebrew get auth => AuthHebrew(this);
	HomeHebrew get home => HomeHebrew(this);
	GoogleHebrew get google => GoogleHebrew(this);
}
```
```
class English {
	const English();
	AuthEnglish get auth => AuthEnglish(this);
	HomeEnglish get home => HomeEnglish(this);
	GoogleEnglish get google => GoogleEnglish(this);
}
```

Classes iv wrote:
```
class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.isSupportedLocale(locale);

  @override
  Future<AppLocalizations> load(Locale locale) =>
      SynchronousFuture<AppLocalizations>(
        AppLocalizations.from(locale),
      );

  @override
  bool shouldReload(CommReadyLocalizationsDelegate old) => true;
}
```
```
class AppLocalizations {
  final strings;

  static const List<Locale> supportedLocales = [
    const Locale.fromSubtags(languageCode: 'en'),
    const Locale.fromSubtags(languageCode: 'he'),
  ];

  static const AppLocalizationsDelegate delegate =
      const AppLocalizationsDelegate();

  static bool isSupportedLocale(Locale locale) {
    final found = supportedLocales.firstWhere(
      (l) => l.languageCode == locale.languageCode,
      orElse: () => null,
    );

    return found != null;
  }

  const AppLocalizations(this.strings);

  factory AppLocalizations.from(Locale locale) {
    switch (locale.languageCode) {
      case 'he':
        return AppLocalizations.hebrew();

      default:
        return AppLocalizations.english();
    }
  }

  factory AppLocalizations.english() =>
      const AppLocalizations(const English());

  factory AppLocalizations.hebrew() =>
      const AppLocalizations(const Hebrew());
}
```
```
extension ContextLocalizationExtensions on BuildContext {
  dynamic get strings => appLocalizations.strings;

  AppLocalizations get appLocalizations =>
      Localizations.of<AppLocalizations>(
        this,
        AppLocalizations,
      );

  List<Locale> get supportedLocales => AppLocalizations.supportedLocales;

  Locale get locale => Localizations.localeOf(this);
}
```

So now as you can see I got `AppLocalizations` with `final dynamic strings`.. I would like to have something like `final AppStrings strings` and `class Hebrew implements AppStrings` `class English implements AppStrings` and all other classes basically the same `class HomeHebrew implements HomeStrings` `class HomeEnglish implements HomeStrings` so I dont need to guess when using `context.strings`.

**Comment by shovelmn12** [comment]
> If I understand your suggestion correctly, then it is already implemented.
> Same type is used for both English and German translations:
> https://github.com/MohiuddinM/i18n/blob/f0428513fcddc6c26d8c96e4c77b9003ba8aef51/example/main.dart#L14

ohh ok only now i noticed that..
the only thing that might be missing is that if i have an extra arg in other language then the "default" one it wont come up..
maybe it should include all params and just have them as null or empty string ??

**Comment by MohiuddinM** [comment]
If a message is missing in a translation, then it gets the message from the default locale
